spring:
  datasource:
    url: jdbc:mysql://10.0.4.56:3306/learn
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com.telsafe: debug