app:
  key: "resafdsf"
  urls: http://baidu.com/1.jpg,http://baidu.com/2.jpg,http://baidu.com/55.jpg
#not work
#  urls:
#    - "http://baidu.com/1.jpg"
#    - "http://baidu.com/2.jpg"
#    - "http://baidu.com/3.jpg"
server.port: 8888