app:
  key: "resafdsf"
  #ok urls: http://baidu.com/1.jpg,http://baidu.com/2.jpg,http://baidu.com/3.jpg
  urls:
    - "http://baidu.com/1.jpg"
    - "http://baidu.com/2.jpg"
    - "http://baidu.com/3.jpg"
  misc:
    a: 一
    b: 二
server.port: 8888